from __future__ import annotations

from pathlib import Path

from SCons.Script import DefaultEnvironment


def _get_project_option(env, name: str, default: str) -> str:
    try:
        value = env.GetProjectOption(name)
    except Exception:
        value = None
    return str(value).strip() if value else default


def _c_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")


def _write_build_info(env) -> None:
    version = _get_project_option(env, "gs_firmware_version", "v1.1.0-s3")
    channel = _get_project_option(env, "gs_firmware_channel", "stable")
    target = _get_project_option(env, "gs_target_board", "ESP32-S3-16MB")

    build_dir = Path(env.subst("$BUILD_DIR"))
    build_dir.mkdir(parents=True, exist_ok=True)
    header_path = build_dir / "build_info.h"

    header = "\n".join(
        [
            "#pragma once",
            "// Auto-generated by scripts/build_info.py",
            f"#define GS_FIRMWARE_VERSION \"{_c_escape(version)}\"",
            f"#define GS_FIRMWARE_CHANNEL \"{_c_escape(channel)}\"",
            f"#define GS_TARGET_BOARD \"{_c_escape(target)}\"",
            "",
        ]
    )
    header_path.write_text(header, encoding="utf-8")
    env.Append(CPPPATH=[str(build_dir)])


env = DefaultEnvironment()
_write_build_info(env)
